---
title: "Distribution fitting investigation"
author: "Nayef Ahmad"
date: "4/4/2020"
output: 
   html_document: 
     keep_md: yes
     code_folding: hide
     toc: true
     toc_float:
       collapsed: false
     toc_folding: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
```

# Libraries
```{r}
library(tidyverse)
library(DT)
library(fitdistrplus)
library(mixtools)
library(here)
library(reticulate)
library(kableExtra)
```

Python modules:

```{r}
# py_install("numpy")
# py_install("pandas")
# py_install("scipy")
```

```{python}
import numpy as np
import pandas as pd 
from scipy import stats 
```


# Data
Sample from a mixture of Weibulls. 

```{r}
p1_shape1 <- .7
p2_shape2 <- 5
p3_mix_prop_1 <- .8
p4_mix_prop_2 <- 1 - p3_mix_prop_1
p5_sample_n <- 300
p6_scale1 <- 1
p7_scale2 <- 2


df <- tibble(id = 1:p5_sample_n, 
             x1_mix = rweibullmix(p5_sample_n,
                                  lambda = c(p3_mix_prop_1, 
                                             p4_mix_prop_2), 
                                  shape = c(p1_shape1,
                                            p2_shape2), 
                                  scale = c(p6_scale1,
                                            p7_scale2)))

df %>% 
   ggplot(aes(x = x1_mix)) + 
   geom_density() + 
   labs(title = "Mixture of Weibulls", 
        subtitle = sprintf("Shape 1: %f  \nShape 2: %f  \nMix prop: %f", 
                           p1_shape1, 
                           p2_shape2, 
                           p3_mix_prop_1))
```

# Distribution fitting

## fitdistrplus 
```{r}
fit <- fitdist(df$x1_mix, "weibull")

fitshape <- fit$estimate[1]
fitscale <- fit$estimate[2]
```

Comparing CDFs: 

First sample from the fitted dist: 
```{r}
x2_single <- rweibull(p5_sample_n,
                      fitshape, 
                      fitscale)
```

Then rearrange data and plot: 

```{r}
df2 <- 
   df %>% 
   mutate(x2_single = x2_single) %>% 
   gather(key = "var", 
          value = "value", 
          -id)
   
df2 %>% 
   ggplot(aes(x = value, 
              colour = var)) + 
   stat_ecdf() + 
   labs(title = "Comparing CDFs",
        subtitle = sprintf("fitted shape: %f  \nfitted scale: %f", 
                           fitshape, 
                           fitscale))
   
```


## scipy.stats 
```{python}
df_py = r.df
x = np.array(df_py['x1_mix'])

# no constraints: 
fit_py1 = stats.exponweib.fit(x)

# constrain a=1
fit_py2 = stats.exponweib.fit(x, f0=1)

# constrain a=1 and loc=0
fit_py3 = stats.exponweib.fit(x, f0=1, floc=0)
```

```{r}
df3 <- 
   tibble(params = c("a", "shape/c", "loc", "scale"), 
          no_constraint = py$fit_py1, 
          constrain_a = py$fit_py2, 
          constrain_a_loc = py$fit_py3) %>%  
   unnest(no_constraint, constrain_a, constrain_a_loc)

df3 %>% 
   kable() %>% 
   kable_styling(bootstrap_options = c("striped",
                                        "condensed", 
                                        "responsive"), 
                  full_width = FALSE, 
                  position = "left")
```

